spring:
  application:
    name: bootiful
  main:
    banner-mode: "off"
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
logging:
  level:
    root: warn
    com.samsoft: debug